### Test 1
GET http://localhost:3000/api/test/run?search=nature
Accept: application/json

### Test 2
GET http://localhost:3000/api/test/run?search=art
Accept: application/json

### Test 3
GET http://localhost:3000/api/test/run?search=something
Accept: application/json
