version: '3.5'

# mpb - moleculer-postgesql-boilerplate
networks:
  mpb_net:

services:
  mpb_db:
    image: postgres:latest
    shm_size: '2g'
    container_name: mpb_db
    restart: unless-stopped
#    env_file: docker-compose.env
    networks:
      - mpb_net
    ports:
      - ${DB_PORT}:5432
#   for big tests only        
#    volumes:
#      - ./mpb_data:/var/lib/postgresql/data
    environment:
#      - TZ=<wanted>
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
